/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PadresRouteImport } from './routes/padres'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as LogrosRouteImport } from './routes/logros'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeccionIdRouteImport } from './routes/leccion.$id'

const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PadresRoute = PadresRouteImport.update({
  id: '/padres',
  path: '/padres',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const LogrosRoute = LogrosRouteImport.update({
  id: '/logros',
  path: '/logros',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeccionIdRoute = LeccionIdRouteImport.update({
  id: '/leccion/$id',
  path: '/leccion/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/logros': typeof LogrosRoute
  '/mapa': typeof MapaRoute
  '/padres': typeof PadresRoute
  '/perfil': typeof PerfilRoute
  '/registro': typeof RegistroRoute
  '/leccion/$id': typeof LeccionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/logros': typeof LogrosRoute
  '/mapa': typeof MapaRoute
  '/padres': typeof PadresRoute
  '/perfil': typeof PerfilRoute
  '/registro': typeof RegistroRoute
  '/leccion/$id': typeof LeccionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/logros': typeof LogrosRoute
  '/mapa': typeof MapaRoute
  '/padres': typeof PadresRoute
  '/perfil': typeof PerfilRoute
  '/registro': typeof RegistroRoute
  '/leccion/$id': typeof LeccionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/logros'
    | '/mapa'
    | '/padres'
    | '/perfil'
    | '/registro'
    | '/leccion/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/logros'
    | '/mapa'
    | '/padres'
    | '/perfil'
    | '/registro'
    | '/leccion/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/logros'
    | '/mapa'
    | '/padres'
    | '/perfil'
    | '/registro'
    | '/leccion/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LogrosRoute: typeof LogrosRoute
  MapaRoute: typeof MapaRoute
  PadresRoute: typeof PadresRoute
  PerfilRoute: typeof PerfilRoute
  RegistroRoute: typeof RegistroRoute
  LeccionIdRoute: typeof LeccionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/padres': {
      id: '/padres'
      path: '/padres'
      fullPath: '/padres'
      preLoaderRoute: typeof PadresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logros': {
      id: '/logros'
      path: '/logros'
      fullPath: '/logros'
      preLoaderRoute: typeof LogrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leccion/$id': {
      id: '/leccion/$id'
      path: '/leccion/$id'
      fullPath: '/leccion/$id'
      preLoaderRoute: typeof LeccionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LogrosRoute: LogrosRoute,
  MapaRoute: MapaRoute,
  PadresRoute: PadresRoute,
  PerfilRoute: PerfilRoute,
  RegistroRoute: RegistroRoute,
  LeccionIdRoute: LeccionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
